/**
 * @param { import(`knex`).Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex(`table_name`).del();
  await knex(`table_name`).insert([
    {
      id: `1`,
      user_id: `1`,
      league_id: `1`,
      name: `Gwaka'moli Crater Gators`,
      faction: `Lizardmen`,
      head_coach: `Kroq-Gar Scalecaller`,
      points: `0`,
      team_value: `990`,
    },
    {
      id: `2`,
      user_id: `1`,
      league_id: `1`,
      name: `Doom Lords`,
      faction: `Chaos Chosen`,
      head_coach: `Kargath Bloodfiend`,
      points: `0`,
      team_value: `1000`,
    },
    {
      id: `3`,
      user_id: `1`,
      league_id: `1`,
      name: `Skavenblight Scramblers`,
      faction: `Skaven`,
      head_coach: `Sneek Sniktails`,
      points: `0`,
      team_value: `950`,
    },
    {
      id: `4`,
      user_id: `1`,
      league_id: `1`,
      name: `Greenfield Grasshuggers`,
      faction: `Halfling`,
      head_coach: `Pip Smallfry`,
      points: `0`,
      team_value: `820`,
    },
    {
      id: `5`,
      user_id: `1`,
      league_id: `1`,
      name: `Elfheim Eagles`,
      faction: `Elven Union`,
      head_coach: `Aelrion Silvermoon`,
      points: `0`,
      team_value: `960`,
    },
    {
      id: `6`,
      user_id: `1`,
      league_id: `1`,
      name: `Crud Creek Nosepickers`,
      faction: `Snotling`,
      head_coach: `Slop the Sludgebringer`,
      points: `0`,
      team_value: `900`,
    },
    {
      id: `7`,
      user_id: `1`,
      league_id: `1`,
      name: `Middenheim Maulers`,
      faction: `Old World Alliance`,
      head_coach: `Harold Ironsides`,
      points: `0`,
      team_value: `970`,
    },
    {
      id: `8`,
      user_id: `1`,
      league_id: `1`,
      name: `Wolfenburg Crypt-Stealers`,
      faction: `Necromantic Horror`,
      head_coach: `Vargan Bloodmoon`,
      points: `0`,
      team_value: `1000`,
    },
    {
      id: `9`,
      user_id: `1`,
      league_id: `1`,
      name: `Kara Temple Harpies`,
      faction: `Amazon`,
      head_coach: `Seraphina Swiftarrow`,
      points: `0`,
      team_value: `980`,
    },
    {
      id: `10`,
      user_id: `1`,
      league_id: `1`,
      name: `Norsca Rampagers`,
      faction: `Norse`,
      head_coach: `Bjorn Frostbeard`,
      points: `0`,
      team_value: `990`,
    },
    {
      id: `11`,
      user_id: `1`,
      league_id: `1`,
      name: `Drakfang Thirsters`,
      faction: `Vampire`,
      head_coach: `Vlad von Drakenhof`,
      points: `0`,
      team_value: `980`,
    },
    {
      id: `12`,
      user_id: `1`,
      league_id: `1`,
      name: `Thunder Valley Greenskins`,
      faction: `Black Orcs`,
      head_coach: `Throgg Bigbash`,
      points: `0`,
      team_value: `960`,
    },
  ]);
};
